remote_theme: pages-themes/minimal@v0.2.0
title: false
name: false
description: <b style="font-size:14px; ">Chad Fisher</b> geospatial data scientist passionate about a sustainable just transition
logo: 'me.png'
