remote_theme: pages-themes/minimal@v0.2.0
title: null
name: Chad Fisher | My Portfolio
description: <b style="font-size:20px; font-family:verdana; font-weight:900">Chad Fisher</b> geospatial data scientist passionate about a sustainable just transition
logo: 'me.png'
