remote_theme: pages-themes/minimal@v0.2.0
title: Chad Fisher
description: geospatial data scientist passionate about a sustainable just transition
<a class="logo" href="/">
    <img src="me.png" alt="photo" width="100px" height="100px" />
</a>
