remote_theme: pages-themes/minimal@v0.2.0
title: My Portfolio
description: <b style="font-size:20px; font-family:verdana; font-weight:900">Chad Fisher</b> geospatial data scientist passionate about climate justice
logo: 'me.png'
